// Generated by npm run generate:oat-source-data. Do not edit directly.

import type { OATSourceData } from "./types.js";

export const lingopOATSourceData: OATSourceData = {
  "guiTextsByScope": {
    "_": [
      "Already have an account?",
      "Browser Voices",
      "Browser Voices load faster. Cloud Voices are usually higher quality.",
      "Cloud Voices",
      "Designed for English speakers",
      "Don't have an account?",
      "Done",
      "Email",
      "For Advanced Users",
      "For Beginners",
      "For Practice",
      "Forgot Password",
      "International Phonetic Alphabet",
      "Language Speaker",
      "Log in",
      "None",
      "Official Spelling",
      "or",
      "Password",
      "Password must be at least 6 characters.",
      "Passwords do not match.",
      "Popular Spelling",
      "Popular Spelling with diacritics",
      "Re-Type Password",
      "Rule-Based Spelling Guide",
      "Sign up",
      "Slow speech sounds better with Browser Voices.",
      "Sorry, that email-password pair didn't match any of our records. Please try again with different details.",
      "Spelling",
      "Tone Numbers"
    ]
  },
  "focusTextsByScope": {},
  "staticFocusTextsByScope": {
    "_": [
      "Where is the toilet?"
    ]
  }
};
