// Generated by npm run generate:oat-source-data. Do not edit directly.

import type { OATSourceData } from "./types.js";

export const lingopOATSourceData: OATSourceData = {
  "guiTextsByScope": {
    "_": [
      "Already have an account?",
      "Annotation Error",
      "Audio",
      "Back",
      "Background Words",
      "Browser Voices",
      "Browser Voices load faster. Cloud Voices are usually higher quality.",
      "Close",
      "Cloud Voices",
      "Copied",
      "Copy",
      "Copy Spelling",
      "Could not load word details.",
      "Designed for English speakers",
      "Don't have an account?",
      "Done",
      "Download",
      "Email",
      "Emoji",
      "Emojis",
      "Error",
      "Fade Background Words",
      "Faded",
      "Feedback",
      "For Advanced Users",
      "For Beginners",
      "For Practice",
      "Forgot Password",
      "Hidden",
      "I want to learn {LANGUAGE}",
      "International Phonetic Alphabet",
      "Language I already know",
      "Language I want to learn",
      "Language Speaker",
      "Learnt",
      "Loading Annotations",
      "Log in",
      "More",
      "No results found.",
      "None",
      "Not Faded",
      "Official Spelling",
      "On Hint",
      "or",
      "Original Text",
      "Password",
      "Password must be at least 6 characters.",
      "Passwords do not match.",
      "Popular Spelling",
      "Popular Spelling with diacritics",
      "Preview",
      "Re-Type Password",
      "Reading Guide",
      "Rule-Based Spelling Guide",
      "Search",
      "Show Original Text",
      "Show Spelling",
      "Sign up",
      "Simplified Chinese Script",
      "Slow speech sounds better with Browser Voices.",
      "Sorry, that email-password pair didn't match any of our records. Please try again with different details.",
      "Speed",
      "Spelling",
      "There is a small cat at my door. It wants to drink some water.",
      "Tone Numbers",
      "Visible",
      "Word details",
      "Word Translations",
      "You can also tap on a word at any time to view its {LANGUAGE} translation."
    ]
  },
  "focusTextsByScope": {
    "_": [
      "There is a small cat at my door. It wants to drink some water."
    ]
  },
  "staticFocusTextsByScope": {
    "_": [
      "There is a small cat at my door. It wants to drink some water.",
      "Where is the toilet?"
    ]
  }
};
