// Generated by npm run generate:oat-source-data. Do not edit directly.

import type { OATSourceData } from "./types.js";

export const lingopOATSourceData: OATSourceData = {
  "guiTextsByScope": {},
  "focusTextsByScope": {},
  "staticFocusTextsByScope": {}
};
