import React, {
  createContext,
  useCallback,
  useContext,
  useRef,
  useState,
  type ReactNode,
} from "react";
import {
  getPrebakedLangPairKey,
  lookupPrebakedTranslation,
} from "../runtime.js";
import type {
  PrebakedTranslations,
  PrebakedTranslationsByLangPair,
} from "../types.js";

export type PrebakedLingoDataContextType = {
  PrebakedT9n: (
    sourceText: string,
    sourceLang: string,
    targetLang: string,
  ) => string;
};

const PrebakedLingoDataContext = createContext<
  PrebakedLingoDataContextType | undefined
>(undefined);

// 20260411: This provider is only for translations. Prebaked annotations are
// generated by the build step but are consumed through the existing annotation
// paths rather than through React context.
export function PrebakedDataProvider({
  children,
  initialTranslationsByLangPair = {},
}: {
  children: ReactNode;
  /**
   * Optional server-provided data for faster first render/SEO. OmniAccess did
   * not populate this yet, but its original provider deliberately allowed it.
   */
  initialTranslationsByLangPair?: PrebakedTranslationsByLangPair;
}) {
  const [translationsByLangPair, setTranslationsByLangPair] =
    useState<PrebakedTranslationsByLangPair>(initialTranslationsByLangPair);
  const translationsRef = useRef(initialTranslationsByLangPair);
  const pendingLangPairsRef = useRef<Set<string>>(new Set());

  const loadTranslations = useCallback(async (langPair: string) => {
    if (
      translationsRef.current[langPair] ||
      pendingLangPairsRef.current.has(langPair)
    ) {
      return;
    }
    pendingLangPairsRef.current.add(langPair);
    try {
      const data = await readTranslationAsset(langPair);
      translationsRef.current = {
        ...translationsRef.current,
        [langPair]: data,
      };
      setTranslationsByLangPair(translationsRef.current);
    } finally {
      pendingLangPairsRef.current.delete(langPair);
    }
  }, []);

  const PrebakedT9n = useCallback(
    (sourceText: string, sourceLang: string, targetLang: string): string => {
      const output = lookupPrebakedTranslation({
        sourceText,
        sourceLang,
        targetLang,
        translationsByLangPair,
      });
      if (output !== undefined) return output;
      void loadTranslations(getPrebakedLangPairKey(sourceLang, targetLang));
      return "…";
    },
    [loadTranslations, translationsByLangPair],
  );

  return (
    <PrebakedLingoDataContext.Provider value={{ PrebakedT9n }}>
      {children}
    </PrebakedLingoDataContext.Provider>
  );
}

async function readTranslationAsset(langPair: string): Promise<PrebakedTranslations> {
  const relativePath = `i18n/var/translations/t.${langPair}.json`;

  // Server rendering cannot fetch a relative browser URL. Return an empty map
  // to suppress that request and mark the pair as attempted; consumers that
  // need translated SSR output can pass `initialTranslationsByLangPair`.
  // Avoid importing Node filesystem modules here because this provider is also
  // compiled into browser bundles.
  if (typeof window === "undefined") {
    return {};
  }

  const fileUrl = `/${relativePath}`;
  const response = await fetch(fileUrl);
  if (!response.ok) {
    console.warn(`Failed to fetch ${fileUrl}`);
    return {}; // Mark the language pair as attempted even when no asset exists.
  }
  return (await response.json()) as PrebakedTranslations;
}

export function usePrebaked(): PrebakedLingoDataContextType {
  const context = useContext(PrebakedLingoDataContext);
  if (context === undefined) {
    throw new Error("usePrebaked must be used within a PrebakedDataProvider");
  }
  return context;
}
